Fixed mkdir invalid argument error when registering workflow
latchbio/latch pull request #186
Opened 2022-10-23 16:40 UTC by CamelCaseCam

I had a bug where workflow registration would fail while creating a log directory and log file because linux (or at least Ubuntu) doesn't allow colons in file names. This change fixes that by replacing the colons in the log path with underscores. I've attached the error logs and a screenshot of the error. 

![image](https://user-images.githubusercontent.com/80700901/197404403-b8a2076e-0051-4d0c-9eac-cee02abb5c24.png)
[.latch_report.tar.gz](https://github.com/latchbio/latch/files/9847043/default.latch_report.tar.gz)

2022-10-28 00:08 UTC, CamelCaseCam commented
@ayushkamat This is the one I was talking about. I've traced this and a similar bug preventing ssh credentials from being added to making the workflow on an NTFS file system running under Linux. NTFS doesn't allow colons in file names, and it doesn't support permissions, so there was no way to register workflows (both --remote and regular was broken)

2022-10-29 00:48 UTC, ayushkamat requested changes
heres a cleaner solution imo, let me know if you have any thoughts and if not ill merge

2022-10-29 00:48 UTC, ayushkamat commented on latch_cli/services/register/register.py
> +    os.makedirs(str(pkg_root) + f"/.logs/{image.replace(':', '_')}", exist_ok=True)
```suggestion
    logs_path = Path(pkg_root).joinpath(".logs").joinpath(image).resolve()
    logs_path.mkdir(exist_ok=True)
```

2022-10-29 00:48 UTC, ayushkamat commented on latch_cli/services/register/register.py
> +        str(pkg_root) + f"/.logs/{image.replace(':', '_')}/docker-build-logs.txt", "w"
```suggestion
        logs_path.joinpath("docker-build-logs.txt"), "w"
```

2022-10-29 01:05 UTC, CamelCaseCam commented
@ayushkamat Looks great! (I've also got a local fix for --remote ssh not working, but it's a bit of a hack, so I'm not sure if it's ready to add)

2022-10-31 23:03 UTC, merged