Docs: Nextflow
latchbio/latch pull request #216
Opened 2023-01-03 00:35 UTC by hannahle

- Nextflow example with line-by-line code explanation
- Nextflow FAQ

2023-01-03 19:24 UTC, ayushkamat requested changes

2023-01-03 19:24 UTC, ayushkamat commented on docs/source/tutorials/nextflow.md
> +![Nextflow Dockerfile](../assets/dockerfile-nextflow.png)
would prefer to make these markdown code snippets and not have images so that ppl can copy/paste

2023-01-03 19:24 UTC, ayushkamat commented on docs/source/tutorials/nextflow.md
> +* **Line 31-38**: are already provided in the boilerplate Dockerfile and are needed to ensure your build envrionment works correctly with Latch.
put these as comments in the code snippet

2023-01-03 19:24 UTC, ayushkamat commented on docs/source/tutorials/nextflow.md
> +Image successfully pulled.
```suggestion
...
```

2023-01-03 19:24 UTC, ayushkamat commented on docs/source/tutorials/nextflow.md
> +This will pull your workflow image built by the Dockerfile, which is handy to verify and reiterate on your build commands.
```suggestion

```

2023-01-03 19:24 UTC, ayushkamat commented on docs/source/tutorials/nextflow.md
> +For example, we can verify that Nextflow is installed correctly by typing:
```suggestion
We can verify that Nextflow is installed correctly by typing
```

2023-01-03 19:24 UTC, ayushkamat commented on docs/source/tutorials/nextflow.md
> +The core logic of a Latch workflow is in the `wf/__init__.py`.
```suggestion
The core logic of a Latch workflow is defined in the file `wf/__init__.py`.
```

2023-01-03 19:24 UTC, ayushkamat commented on docs/source/tutorials/nextflow.md
> +To wrap the Nextflow workflow inside a Latch workflow, first import the necessary dependencies
```suggestion
To wrap the Nextflow workflow inside a Latch workflow, first import the necessary dependencies:
```

2023-01-03 19:24 UTC, ayushkamat commented on docs/source/tutorials/nextflow.md
> +Next, let's define our task:
```suggestion
Next, define the task:
```

2023-01-03 19:24 UTC, ayushkamat commented on docs/source/tutorials/nextflow.md
> +![Nextflow Task](../assets/nextflow-task.png)
same comments as above

2023-01-03 19:24 UTC, ayushkamat commented on docs/source/tutorials/nextflow.md
> +    """
may wanna put some documentation here

2023-01-03 19:24 UTC, ayushkamat commented on docs/source/tutorials/nextflow.md
> +To expose workflow parameters to a user-friendly workflow GUI, you can use the `LatchMetadata` object. An important point to note is that all workflow arguments need to be added to the `parameters` k
```suggestion
To expose workflow parameters in a user-friendly workflow GUI, you can use the `LatchMetadata` object. An important point to note is that all workflow arguments need to be added to the `parameters` key of LatchMetadata for them to display on the GUI. For an exhaustive list of how workflow arguments and their respective Python types map to a front-end component, see [Customizing Your Interface](../basics/customizing_interface.md)
```

2023-01-03 19:24 UTC, ayushkamat commented on docs/source/tutorials/nextflow.md
> +This will give us:
```suggestion
This will give us
```

2023-01-03 19:24 UTC, ayushkamat commented on docs/source/tutorials/nextflow.md
> +* parallelized CSV-to-batch execution
```suggestion
* a no-code interface,
* managed cloud infrastructure for workflow execution,
* a dedicated API endpoint for programmatic execution,
* hosted documentation, and
* parallelized CSV-to-batch execution.
```

2023-01-03 19:24 UTC, ayushkamat commented on docs/source/tutorials/nextflow.md
> +Once registration finishes, you can navigate to [Latch](https://console.latch.bio/workflows) to run your workflow.
```suggestion
Once registration finishes, you can navigate to the [Latch Console](https://console.latch.bio/workflows) to run your workflow.
```

2023-01-03 19:24 UTC, ayushkamat commented on docs/source/tutorials/nextflow.md
> +Below we aim to provide answers to the most commonly asked questions about porting a Nextflow pipeline to Latch:
```suggestion
```

2023-01-03 19:24 UTC, ayushkamat commented on docs/source/tutorials/nextflow.md
> +    One disadvantage of this, however, is all processes are run on a single machine with fixed compute resource. If parallelization of individual processes across multiple machines is desired, it is
```suggestion
    One disadvantage of this, however, is that all processes are run on a single machine with fixed compute resources. If parallelization of individual processes across multiple machines is desired, it is beneficial to refactor each process into its individual task. This is quick to do with the [SDK's remote debugging toolkit](../basics/local_development.md).
```

2023-02-06 23:58 UTC, maximsmol commented on docs/source/tutorials/nextflow.md
> +Nextflow is a popular framework for orchestrating bioinformatics workflows. In this tutorial, we will walk through how you can package an existing Nextflow script in Latch Python SDK!
why doe

2023-02-07 00:20 UTC, maximsmol commented on docs/source/tutorials/nextflow.md
> +latch register -r .
```suggestion
latch register --remote .
```

2023-02-07 00:21 UTC, maximsmol commented on docs/source/tutorials/nextflow.md
> +  * Here, we are passing in the remote filepath (e.g. `latch:///rnaseq-nf/ggal_gut_1.fq`) to the `Path` object to resolve its filepath in the task machine.
uh no we're not
`latch://` urls don't work in pathlib obviously

2023-02-07 00:22 UTC, maximsmol commented on docs/source/tutorials/nextflow.md
> +latch test-data upload rnaseq-nf/data/ggal
uhh this works? bruh

2023-02-07 00:23 UTC, maximsmol commented on docs/source/tutorials/nextflow.md
> +            LatchFile("s3://test-data/6064/rnaseq-nf/data/ggal/ggal_gut_1.fq"),
explain where `6064` came from

2023-03-20 19:39 UTC, closed without merging