Nextflow docs: BLAST example
latchbio/latch pull request #218
Opened 2023-01-06 03:52 UTC by hannahle

2023-01-13 21:19 UTC, jvfe commented on docs/source/tutorials/nextflow.md
> +You can verify the dependencies installation by listing our the environment:
```suggestion
You can verify the dependencies installation by listing the environments:
```

2023-01-13 21:19 UTC, jvfe commented on docs/source/tutorials/nextflow.md
> +* **Line 30**: uses Micromamba to install the dependencies as spefieid in `/root/blast-nf/conda.yml`.
```suggestion
* **Line 30**: uses Micromamba to install the dependencies as specified in `/root/blast-nf/conda.yml`.
```

2023-01-13 21:19 UTC, jvfe commented on docs/source/tutorials/nextflow.md
> +Enter an interative shell:
```suggestion
Enter an interactive shell:
```

2023-02-07 00:29 UTC, maximsmol requested changes
a lot of comments from #216 apply here

---

`blast-nf-wf.png` has overlapping text somehow

---

also use unabbreviated command line parameters

2023-02-07 00:29 UTC, maximsmol commented on docs/source/tutorials/nextflow.md
> +    chmod 777 /usr/bin/nextflow
```suggestion
    chmod u+x /usr/bin/nextflow 
```

2023-02-07 00:29 UTC, maximsmol commented on docs/source/tutorials/nextflow.md
> +        name="John von Neumann",
?

2023-02-07 00:29 UTC, maximsmol commented on docs/source/tutorials/nextflow.md
> +        email="hungarianpapi4@gmail.com",
???

2023-03-20 19:39 UTC, closed without merging