nextflow mvp
latchbio/latch pull request #358
Opened 2023-12-01 18:45 UTC by kennyworkman

rage
rage
against the dying of the light

2023-12-09 21:58 UTC, ayushkamat requested changes
didnt look too closely at the shared logic

2023-12-09 21:58 UTC, ayushkamat commented on latch_cli/nextflow/workflow.py
> +        def create_bindings(
move this and `global_start_node` to top level

2023-12-09 21:58 UTC, ayushkamat commented on latch_cli/nextflow/workflow.py
> +                ...
del, make it a todo if you plan on supporting this in the future

2024-03-16 22:17 UTC, rahuldesai1 reviewed
minor comments

have some questions about how the branching works, mostly for my understanding
also don't really understand NextflowProcessPost/PreAdapterTask

lets sync on Monday

2024-06-11 17:50 UTC, closed without merging