Submit SKIPPED status to vacuole
latchbio/latch pull request #404
Opened 2024-03-21 18:38 UTC by rahuldesai1

2024-03-21 21:16 UTC, AidanAbd approved these changes

2024-03-21 21:16 UTC, AidanAbd commented on latch_cli/utils/workflow.py
> +    arr_retry = None if len(s) <= 4 else s[4]
there are perhaps more fucked up than you think -- check what nucleus-logs does.

2024-03-22 17:24 UTC, maximsmol requested changes

2024-03-22 17:24 UTC, maximsmol commented on latch_cli/utils/workflow.py
> +def override_task_status(status: str) -> None:
should probably be made private?

2024-03-22 17:24 UTC, maximsmol commented on latch_cli/utils/workflow.py
> +    r"^(?P<token>[a-zA-Z0-9]+)-(?P<node_name>(n\d+-\d+-)*n\d+)-(?P<retry>\d)+(?:-(?P<arr_index>\d+))?(?:-(?P<arr_retry>\d+))?$"
would prefer an extended regex like

```
r"""
^(
    (?P<token>[a-zA-Z0-9]+)
		-
		(?P<node_name>
				(
						n
						[0-9]+
						-
						[0-9]+
						-
				)*
				n
				[0-9]+
		)
		-
		...
)
"""
```

2024-04-01 18:22 UTC, ayushkamat requested changes
smol things

2024-04-01 18:22 UTC, ayushkamat commented on latch_cli/utils/workflow.py
> +        pod_name = f.read().strip()
```suggestion
    pod_name = Path("/etc/hostname").read_text().strip()
```

2024-04-02 19:43 UTC, merged