Added error message when initializing illegal workflow name
latchbio/latch pull request #78
Opened 2022-06-03 22:42 UTC by CamelCaseCam

Right now, you get a cryptic error message when you register a workflow with an illegal name (see #60). I've added a check when initializing a workflow that prints a clear error message if you attempt to initialize a workflow with an illegal name (I've defined an illegal name as anything with capital letters or that ends in _ or -, though this isn't exhaustive). I haven't tested this, since the repository doesn't give build instructions, but it's only three if statements.

2022-06-03 22:56 UTC, kennyworkman requested changes
thanks for the contribution, small comments

2022-06-03 22:56 UTC, kennyworkman commented on latch/cli/main.py
> +    #Workflow name must not contain capitals or end in a hyphen or underscore. If it does, we should throw an error
small stylistic comment - add a space after `#` and comment text

2022-06-03 23:21 UTC, ayushkamat requested changes

2022-06-03 23:21 UTC, ayushkamat commented on latch/cli/main.py
> +    if pkg_name[-1] is '-' or pkg_name[-1] is '_':
just explicitly match against the regex here:
https://github.com/distribution/distribution/blob/ffbd94cbe269828d76a6698a666e9d09ba30bb91/reference/regexp.go#L41

2022-06-04 23:17 UTC, CamelCaseCam commented
There we go, how about this?

2022-06-05 02:00 UTC, kennyworkman commented
@CamelCaseCam last small thing

2022-06-05 14:45 UTC, CamelCaseCam commented
@kennyworkman I can't see whatever you added

2022-06-05 15:44 UTC, kennyworkman requested changes

2022-06-05 15:44 UTC, kennyworkman commented
@CamelCaseCam check again?

2022-06-05 16:18 UTC, CamelCaseCam commented
@kennyworkman How about this?

2022-06-05 21:28 UTC, kennyworkman approved these changes

2022-06-05 21:30 UTC, merged