Update register() to use args and kwargs
latchbio/latch pull request #92
Opened 2022-06-27 22:59 UTC by imbatraman

Updating def register() to *args and **kwargs. args for pkg_root and kwargs for remote

TODO:
- test
- update doc strings

2022-06-28 23:43 UTC, kennyworkman commented
hey @imbatraman can you provide more context on this change?

2022-06-29 00:31 UTC, imbatraman commented
> 

hey @kennyworkman - this one relates to my chat with @ayushkamat on updating `latch register` to work on either the current working dir (if no args are provided) or the dir provided

Here's an extract from the chat:

> add the ability to run latch register  without any arguments and have that run latch register on the current working directory 
> right now, a call to latch register requires the user to specify which directory they want to be registered, and requires the user to run the command while outside the directory in question

2022-06-29 01:00 UTC, ayushkamat requested changes

2022-06-29 01:03 UTC, imbatraman commented on latch_cli/services/register/register.py
>  def register(
sure thing - i'll change it there

2022-06-30 16:25 UTC, ayushkamat requested changes
One small thing: change the @click.argument decorator for the function so that the pkg_root argument isn't required - see the Click documentation for how to do this

2022-07-20 16:49 UTC, closed without merging